#!/bin/sh

#taking input from the argument
chord=$1

#colors

bold='[1m'
black='[30m'
red='[31m'
green='[32m'
yellow='[33m'
blue='[34m'
magenta='[35m'
cyan='[36m'
white='[37m'
grey='[90m'
reset='[0m'

#selecting the appropriate chord diagram
case $chord in
	[Aa]) cat <<-EOF
	
	e |------0------|
	${blue}${bold}B |------2------|${reset}
	${blue}${bold}G |------2------|${reset}
	${blue}${bold}D |------2------|${reset}
	A |------0------|
	${red}E |------x------|${reset}
	
	EOF
	;;
	
	[Aa]maj7) cat <<-EOF
	${white}e |------0------|
	${blue}${bold}B |------2------|${reset}
	${blue}${bold}G |------1------|${reset}
	${blue}${bold}D |------2------|${reset}
	A |------0------|
	${red}E |------x------|${reset}
	EOF
	;;
	
	[Aa]7) cat <<-EOF
	e |------0------|
	${blue}${bold}B |------2------|${reset}
	G |------0------|
	${blue}${bold}D |------2------|${reset}
	A |------0------|
	${red}E |------x------|${reset}
	EOF
	;;
	
	[Aa]m) cat <<-EOF
	e |------0------|
	${blue}${bold}B |------1------|${reset}
	${blue}${bold}G |------2------|${reset}
	${blue}${bold}D |------2------|${reset}
	A |------0------|
	${red}E |------x------|${reset}
	EOF
	;;
	
	[Aa]m7) cat <<-EOF
	e |------0------|
	${blue}${bold}B |------1------|${reset}
	G |------0------|
	${blue}${bold}D |------2------|${reset}
	A |------0------|
	${red}E |------x------|${reset}
	EOF
	;;
	
	[Bb]) cat <<-EOF
	${blue}${bold}e |------2------|${reset}
	${blue}${bold}B |------4------|${reset}
	${blue}${bold}G |------4------|${reset}
	D${blue}${bold} |------4------|${reset}
	A |------x------|
	${red}E |------x------|${reset}
	EOF
	;;
	
	[Bb]maj7) cat <<-EOF
	${red}e |------x------|${reset}
	B |------0------|
	${blue}${bold}G |------3------|${reset}
	${blue}${bold}D |------1------|${reset}
	${blue}${bold}A |------2------|${reset}
	${blue}${bold}E |------2------|${reset}
	EOF
	;;

	[Bb]7) cat <<-EOF
	${blue}${bold}e |------2------|${reset}
	B |------0------|
	${blue}${bold}G |------2------|${reset}
	${blue}${bold}D |------1------|${reset}
	${blue}${bold}A |------2------|${reset}
	${red}E |------x------|${reset}
	EOF
	;;
	
	[Bb]m) cat <<-EOF
	${blue}${bold}e |------2------|${reset}
	${blue}${bold}B |------3------|${reset}
	${blue}${bold}G |------4------|${reset}
	${blue}${bold}D |------4------|${reset}
	${red}A |------x------|${reset}
	${red}E |------x------|${reset}
	EOF
	;;
	
	[Bb]m7) cat <<-EOF
	${blue}${bold}e |------2------|${reset}
	B |------0------|
	${blue}${bold}G |------2------|${reset}
	D |------0------|
	${blue}${bold}A |------2------|${reset}
	${red}E |------x------|${reset}
	EOF
	;;
	
	[Cc]) cat <<-EOF   
	e |------0------|                                            
	${blue}${bold}B |------1------|${reset}
	G |------0------|
	${blue}${bold}D |------2------|${reset}
	${blue}${bold}A |------3------|${reset}
	${red}E |------x------|${reset}
	EOF
	;;
	
	[Cc]maj7) cat <<-EOF   
	e |------0------|                                            
	B |------0------|
	G |------0------|
	${blue}${bold}D |------2------|${reset}
	${blue}${bold}A |------3------|${reset}
	${red}E |------x------|${reset}
	EOF
	;;
	
	[Cc]7) cat <<-EOF   
	e |------0------|                                            
	${blue}${bold}B |------1------|${reset}
	${blue}${bold}G |------3------|${reset}
	${blue}${bold}D |------2------|${reset}
	${blue}${bold}A |------3------|${reset}
	${red}E |------x------|${reset}
	EOF
	;;
	
	[Cc]m) cat <<-EOF   
	${red}e |------x------|${reset}     
	${red}B |------x------|${reset}
	G |------0------|
	${blue}${bold}D |------1------|${reset}
	${blue}${bold}A |------3------|${reset}
	${red}E |------x------|${reset}
	EOF
	;;
	
	[Cc]m7) cat <<-EOF   
	${red}e |------x------|${reset}                                            
	${red}B |------x------|${reset}
	${blue}${bold}G |------3------|${reset}
	${blue}${bold}D |------1------|${reset}
	${blue}${bold}A |------3------|${reset}
	${red}E |------x------|${reset}
	EOF
	;;
	
	[Dd]) cat <<-EOF   
	${blue}${bold}e |------2------|${reset}                                            
	${blue}${bold}B |------3------|${reset}
	${blue}${bold}G |------2------|${reset}
	D |------0------|
	${red}A |------x------|${reset}
	${red}E |------x------|${reset}
	EOF
	;;
	
	[Dd]maj7) cat <<-EOF   
	${blue}${bold}e |------2------|${reset}                                            
	${blue}${bold}B |------2------|${reset}
	${blue}${bold}G |------2------|${reset}
	D |------0------|
	${red}A |------x------|${reset}
	${red}E |------x------|${reset}
	EOF
	;;
	
	[Dd]7) cat <<-EOF   
	${blue}${bold}e |------2------|${reset}
	${blue}${bold}B |------1------|${reset}
	${blue}${bold}G |------2------|${reset}
	D |------0------|
	${red}A |------x------|${reset}
	${red}E |------x------|${reset}
	EOF
	;;
	
	[Dd]m) cat <<-EOF   
	${blue}${bold}e |------1------|${reset}                                     
	${blue}${bold}B |------3------|${reset}
	${blue}${bold}G |------2------|${reset}
	D |------0------|
	${red}A |------x------|${reset}
	${red}E |------x------|${reset}
	EOF
	;;
	
	[Dd]m7) cat <<-EOF   
	${blue}${bold}e |------1------|${reset}                                          
	${blue}${bold}B |------1------|${reset}
	${blue}${bold}G |------2------|${reset}
	D |------0------|
	${red}A |------x------|${reset}
	${red}E |------x------|${reset}
	EOF
	;;
	
	[Ee]) cat <<-EOF   
	e |------0------|                                            
	B |------0------|
	${blue}${bold}G |------1------|${reset}
	${blue}${bold}D |------2------|${reset}
	${blue}${bold}A |------2------|${reset}
	E |------0------|
	EOF
	;;
	
	[Ee]maj7) cat <<-EOF   
	e |------0------|                                            
	B |------0------|
	${blue}${bold}G |------1------|${reset}
	${blue}${bold}D |------1------|${reset}
	${blue}${bold}A |------2------|${reset}
	E |------0------|
	EOF
	;;
	
	[Ee]7) cat <<-EOF   
	e |------0------|                                            
	B |------0------|
	${blue}${bold}G |------1------|${reset}
	D |------0------|
	${blue}${bold}A |------2------|${reset}
	E |------0------|
	EOF
	;;
	
	[Ee]m) cat <<-EOF   
	e |------0------|                                            
	B |------0------|
	G |------0------|
	${blue}${bold}D |------2------|${reset}
	${blue}${bold}A |------2------|${reset}
	E |------0------|
	EOF
	;;
	
	[Ee]m7) cat <<-EOF   
	e |------0------|                                            
	${blue}${bold}B |------3------|${reset}
	G |------0------|
	${blue}${bold}D |------2------|${reset}
	${blue}${bold}A |------2------|${reset}
	E |------0------|
	EOF
	;;
	
	[Ff]) cat <<-EOF   
	${blue}${bold}e |------1------|${reset}                                    
	${blue}${bold}B |------1------|${reset}
	${blue}${bold}G |------2------|${reset}
	${blue}${bold}D |------3------|${reset}
	${red}A |------x------|
	${red}E |------x------|
	EOF
	;;
	
	[Ff]maj7) cat <<-EOF   
	e |------0------|                                            
	${blue}${bold}B |------1------|${reset}
	${blue}${bold}G |------2------|${reset}
	${blue}${bold}D |------3------|${reset}
	${red}A |------x------|${reset}
	${red}E |------x------|${reset}
	EOF
	;;
	
	[Ff]7) cat <<-EOF   
	${blue}${bold}e |------1------|${reset}                                            
	${blue}${bold}B |------1------|${reset}
	${blue}${bold}G |------2------|${reset}
	${blue}${bold}D |------1------|${reset}
	${blue}${bold}A |------3------|${reset}
	${blue}${bold}E |------1------|${reset}
	EOF
	;;
	
	[Ff]m) cat <<-EOF   
	${blue}${bold}e |------1------|${reset}                                    
	${blue}${bold}B |------1------|${reset}
	${blue}${bold}G |------1------|${reset}
	${blue}${bold}D |------3------|${reset}
	${red}A |------x------|${reset}
	${red}E |------x------|${reset}
	EOF
	;;
	
	[Ff]m7) cat <<-EOF   
	${blue}${bold}e |------1------|${reset}                                           
	${blue}${bold}B |------1------|${reset}
	${blue}${bold}G |------1------|${reset}
	${blue}${bold}D |------1------|${reset}
	${blue}${bold}A |------3------|${reset}
	${blue}${bold}E |------1------|${reset}
	EOF
	;;
	
	[Gg]) cat <<-EOF   
	${blue}${bold}e |------3------|${reset}                                           
	B |------0------|
	G |------0------|
	D |------0------|
	${blue}${bold}A |------2------|${reset}
	${blue}${bold}E |------3------|${reset}
	EOF
	;;
	
	[Gg]maj7) cat <<-EOF   
	${blue}${bold}e |------2------|${reset}                                          
	B |------0------|
	G |------0------|
	D |------0------|
	${red}A |------x------|${reset}
	${blue}${bold}E |------3------|${reset}
	EOF
	;;
	
	[Gg]7) cat <<-EOF   
	${blue}${bold}e |------1------|${reset}                                            
	B |------0------|
	G |------0------|
	D |------0------|
	${blue}${bold}A |------2------|${reset}
	${blue}${bold}E |------3------|${reset}
	EOF
	;;
	
	[Gg]m) cat <<-EOF   
	${blue}${bold}e |------3------|${reset}                                          
	${blue}${bold}B |------3------|${reset}
	${blue}${bold}G |------3------|${reset}
	D |------0------|
	${red}A |------x------|${reset}
	${red}E |------x------|${reset}
	EOF
	;;
	
	[Gg]m7) cat <<-EOF   
	e |------0------|                                            
	${blue}${bold}B |------3------|${reset}
	G |------0------|
	${blue}${bold}D |------3------|${reset}
	${blue}${bold}A |------1------|${reset}
	${red}E |------x------|${reset}
	EOF
	;;
	
	-v) cat <<-EOF
	version 0.1
	EOF
	;;
	
	*) cat <<-EOF
	${yellow}Please entere a valid chord${reset}
	EOF
	;;
	
	-h) cat <<-EOF
	${yellow}Hello this is chords!! how can I help you?${reset}
	EOF
	;;
	
	-a) cat <<-EOF
	${yellow}Made by RC${reset}
	EOF
	;;
esac

#cat <<EOF
#${green}$draw${reset}
#EOF
